import 'dart:io';
import 'dart:async';
import 'package:flutter/foundation.dart';
import 'package:flutter/material.dart';
import 'package:ai_fake_news_detector/services/media_analysis_channel.dart';
import 'package:ai_fake_news_detector/utils/global.colors.dart';

/// Screen for showing upload progress and processing status.
///
/// Expects route arguments:
/// ```dart
/// {
///   'filePath'  : String,
///   'fileType'  : String,   // 'image' | 'video'
///   'fileSize'  : int,
///   'taskId'    : String,   // Fix 6 – generated by caller via startAnalysis()
/// }
/// ```
class ProcessingScreen extends StatefulWidget {
  const ProcessingScreen({super.key});

  @override
  State<ProcessingScreen> createState() => _ProcessingScreenState();
}

class _ProcessingScreenState extends State<ProcessingScreen> {
  bool _hasNavigated = false;
  bool _isDisposed = false;

  // Fix 6 – taskId is now read from route arguments, not left null.
  String? _taskId;
  String? _filePath;
  String? _fileType;

  String _status = 'uploading';
  double _progress = 0.0;
  int _frameCount = 0;

  // Named callbacks so we can unsubscribe cleanly (Fix 1).
  late final void Function(Map<String, dynamic>) _onResult;
  late final void Function(Map<String, dynamic>) _onError;
  late final void Function(Map<String, dynamic>) _onVideoFrameResult;
  late final void Function(Map<String, dynamic>) _onVideoFrameError;
  StreamSubscription<AnalysisProgressEvent>? _progressSub;

  @override
  void initState() {
    super.initState();
    debugPrint('ProcessingScreen: initState called');

    _onResult = (resultData) {
      debugPrint('ProcessingScreen: Analysis result received: $resultData');
      if (!_hasNavigated && mounted && !_isDisposed) {
        _hasNavigated = true;
        // Pass file metadata alongside result so MediaResultPage can display
        // the preview without re-fetching anything (Fix 2).
        final args = {
          'filePath': _filePath,
          'fileType': _fileType,
          ...resultData,
        };
        Navigator.pushReplacementNamed(
          context,
          '/media-result',
          arguments: args,
        );
      }
    };

    _onError = (errorData) {
      debugPrint('ProcessingScreen: Analysis error received: $errorData');
      if (mounted && !_isDisposed) {
        setState(() => _status = 'failed');
      }
    };

    _onVideoFrameResult = (resultData) {
      debugPrint('ProcessingScreen: Video frame result received: $resultData');
      if (!_hasNavigated && mounted && !_isDisposed) {
        _hasNavigated = true;
        // Pass file metadata alongside result so MediaResultPage can display
        // the preview without re-fetching anything (Fix 2).
        final args = {
          'filePath': _filePath,
          'fileType': _fileType,
          ...resultData,
        };
        Navigator.pushReplacementNamed(
          context,
          '/media-result',
          arguments: args,
        );
      }
    };

    _onVideoFrameError = (errorData) {
      debugPrint('ProcessingScreen: Video frame error received: $errorData');
      if (mounted && !_isDisposed) {
        setState(() => _status = 'failed');
      }
    };

    // Fix 1 – add, don't replace.
    MediaAnalysisChannel.addOnAnalysisResult(_onResult);
    MediaAnalysisChannel.addOnAnalysisError(_onError);
    MediaAnalysisChannel.addOnVideoFrameResult(_onVideoFrameResult);
    MediaAnalysisChannel.addOnVideoFrameError(_onVideoFrameError);
    debugPrint('ProcessingScreen: Listeners registered');

    // Fix 2 – drive the progress UI from the stream.
    _progressSub =
        MediaAnalysisChannel.progressStream.listen((event) {
      if (!mounted || _isDisposed) return;
      if (event.taskId != _taskId) return;
      debugPrint('ProcessingScreen: Progress event received: status=${event.status}, progress=${event.progress}');
      setState(() {
        _status = event.status;
        _progress = event.progress;
      });
    });

    // Route args are not available in initState; defer to first frame.
    WidgetsBinding.instance.addPostFrameCallback((_) => _readArgs());
  }

  void _readArgs() {
    final args = ModalRoute.of(context)?.settings.arguments
        as Map<String, dynamic>?;
    debugPrint('ProcessingScreen: Route arguments: $args');
    
    if (args != null) {
      setState(() {
        _taskId = args['taskId'] as String?;
        _filePath = args['filePath'] as String?;
        _fileType = args['fileType'] as String?;
      });
      debugPrint('ProcessingScreen: TaskId=$_taskId, FilePath=$_filePath, FileType=$_fileType');
    }
  }

  @override
  void dispose() {
    debugPrint('ProcessingScreen: dispose called');
    _isDisposed = true;
    // Fix 1 – remove our specific callbacks, not everyone's.
    MediaAnalysisChannel.removeOnAnalysisResult(_onResult);
    MediaAnalysisChannel.removeOnAnalysisError(_onError);
    MediaAnalysisChannel.removeOnVideoFrameResult(_onVideoFrameResult);
    MediaAnalysisChannel.removeOnVideoFrameError(_onVideoFrameError);
    _progressSub?.cancel();
    debugPrint('ProcessingScreen: Listeners removed');
    super.dispose();
  }

  @override
  Widget build(BuildContext context) {
    return Scaffold(
      appBar: AppBar(
        backgroundColor: GlobalColors.mainColor,
        title: const Text(
          'Processing',
          style: TextStyle(color: Colors.white, fontWeight: FontWeight.bold),
        ),
        leading: IconButton(
          icon: const Icon(Icons.arrow_back, color: Colors.white),
          onPressed: _showCancelDialog,
        ),
      ),
      body: _buildBody(),
    );
  }

  Widget _buildBody() {
    return SingleChildScrollView(
      padding: const EdgeInsets.all(16),
      child: Column(
        crossAxisAlignment: CrossAxisAlignment.stretch,
        children: [
          _buildFilePreview(),
          const SizedBox(height: 24),
          _buildProgressIndicator(),
          const SizedBox(height: 16),
          _buildStatusMessage(),
          const SizedBox(height: 24),
          _buildCancelButton(),
        ],
      ),
    );
  }

  Widget _buildFilePreview() {
    if (_filePath == null) return const SizedBox.shrink();
    if (_fileType == 'image') {
      return ClipRRect(
        borderRadius: BorderRadius.circular(12),
        child: Image.file(
          File(_filePath!),
          height: 240,
          fit: BoxFit.cover,
          errorBuilder: (_, __, ___) => const SizedBox.shrink(),
        ),
      );
    }
    // For video, show a placeholder (full controller not needed here).
    return Container(
      height: 240,
      decoration: BoxDecoration(
        color: Colors.black87,
        borderRadius: BorderRadius.circular(12),
      ),
      child: const Center(
        child: Icon(Icons.videocam, color: Colors.white54, size: 64),
      ),
    );
  }

  Widget _buildProgressIndicator() {
    if (_status == 'uploading') {
      return Column(
        children: [
          LinearProgressIndicator(
            value: _progress,
            backgroundColor: Colors.grey[300],
            valueColor:
                AlwaysStoppedAnimation<Color>(GlobalColors.mainColor),
            minHeight: 8,
          ),
          const SizedBox(height: 8),
          Text(
            '${(_progress * 100).toStringAsFixed(0)}%',
            style: TextStyle(
              fontSize: 16,
              fontWeight: FontWeight.bold,
              color: GlobalColors.mainColor,
            ),
          ),
        ],
      );
    }
    if (_status == 'extracting_frames') {
      return Column(
        children: [
          SizedBox(
            width: 80,
            height: 80,
            child: CircularProgressIndicator(
              strokeWidth: 6,
              valueColor:
                  AlwaysStoppedAnimation<Color>(GlobalColors.mainColor),
            ),
          ),
          const SizedBox(height: 16),
          Text(
            'Extracting frames…',
            style: TextStyle(
              fontSize: 18,
              fontWeight: FontWeight.bold,
              color: GlobalColors.mainColor,
            ),
          ),
          if (_frameCount > 0) ...[
            const SizedBox(height: 8),
            Text(
              '$_frameCount frames extracted',
              style: TextStyle(
                fontSize: 14,
                color: Colors.grey[600],
              ),
            ),
          ],
        ],
      );
    }
    if (_status == 'uploading_frames') {
      return Column(
        children: [
          LinearProgressIndicator(
            value: _progress,
            backgroundColor: Colors.grey[300],
            valueColor:
                AlwaysStoppedAnimation<Color>(GlobalColors.mainColor),
            minHeight: 8,
          ),
          const SizedBox(height: 8),
          Text(
            'Uploading frames… ${(_progress * 100).toStringAsFixed(0)}%',
            style: TextStyle(
              fontSize: 16,
              fontWeight: FontWeight.bold,
              color: GlobalColors.mainColor,
            ),
          ),
          if (_frameCount > 0) ...[
            const SizedBox(height: 8),
            Text(
              'Uploading $_frameCount frames',
              style: TextStyle(
                fontSize: 14,
                color: Colors.grey[600],
              ),
            ),
          ],
        ],
      );
    }
    if (_status == 'processing') {
      return Column(
        children: [
          SizedBox(
            width: 80,
            height: 80,
            child: CircularProgressIndicator(
              strokeWidth: 6,
              valueColor:
                  AlwaysStoppedAnimation<Color>(GlobalColors.mainColor),
            ),
          ),
          const SizedBox(height: 16),
          Text(
            'Processing…',
            style: TextStyle(
              fontSize: 18,
              fontWeight: FontWeight.bold,
              color: GlobalColors.mainColor,
            ),
          ),
        ],
      );
    }
    if (_status == 'failed') {
      return Icon(Icons.error_outline, color: Colors.red[400], size: 64);
    }
    return const SizedBox.shrink();
  }

  Widget _buildStatusMessage() {
    final messages = {
      'uploading': 'Uploading file…',
      'extracting_frames': 'Extracting video frames…',
      'uploading_frames': 'Uploading frames to server…',
      'processing': 'Analysing media, please wait…',
      'failed': 'Something went wrong. You can retry or go back.',
      'cancelled': 'Upload cancelled.',
    };
    final message = messages[_status] ?? 'Starting…';
    final isActive = _status == 'uploading' || _status == 'extracting_frames' || _status == 'uploading_frames' || _status == 'processing';

    return Container(
      padding: const EdgeInsets.all(16),
      decoration: BoxDecoration(
        color: Colors.grey[100],
        borderRadius: BorderRadius.circular(12),
        border: Border.all(color: Colors.grey[300]!),
      ),
      child: Row(
        mainAxisAlignment: MainAxisAlignment.center,
        children: [
          if (isActive)
            Padding(
              padding: const EdgeInsets.only(right: 12),
              child: SizedBox(
                width: 20,
                height: 20,
                child: CircularProgressIndicator(
                  strokeWidth: 2,
                  valueColor:
                      AlwaysStoppedAnimation<Color>(GlobalColors.mainColor),
                ),
              ),
            ),
          Flexible(
            child: Text(
              message,
              style: const TextStyle(
                  fontSize: 16, fontWeight: FontWeight.w500),
              textAlign: TextAlign.center,
            ),
          ),
        ],
      ),
    );
  }

  Widget _buildCancelButton() {
    final isActive = _status == 'uploading' || _status == 'extracting_frames' || _status == 'uploading_frames' || _status == 'processing';
    return ElevatedButton(
      onPressed: isActive ? _showCancelDialog : null,
      style: ElevatedButton.styleFrom(
        backgroundColor: Colors.red[400],
        foregroundColor: Colors.white,
        padding: const EdgeInsets.symmetric(vertical: 16),
        shape: RoundedRectangleBorder(
            borderRadius: BorderRadius.circular(12)),
      ),
      child: const Text('Cancel',
          style: TextStyle(fontSize: 16, fontWeight: FontWeight.bold)),
    );
  }

  void _showCancelDialog() {
    debugPrint('ProcessingScreen: Showing cancel dialog');
    showDialog(
      context: context,
      builder: (ctx) => AlertDialog(
        title: const Row(
          children: [
            Icon(Icons.warning_amber_rounded, color: Colors.orange),
            SizedBox(width: 8),
            Text('Cancel Upload?'),
          ],
        ),
        content: const Text(
          'Are you sure you want to cancel? This action cannot be undone.',
        ),
        actions: [
          TextButton(
            onPressed: () => Navigator.pop(ctx),
            child: const Text('Continue'),
          ),
          ElevatedButton(
            onPressed: () {
              Navigator.pop(ctx);
              debugPrint('ProcessingScreen: Cancel button pressed for taskId: $_taskId');
              // Fix 6 – taskId is now always set, so this call is safe.
              if (_taskId != null) {
                MediaAnalysisChannel.cancelAnalysis(_taskId!);
              }
              Navigator.pop(context);
            },
            style: ElevatedButton.styleFrom(
              backgroundColor: Colors.red[400],
              foregroundColor: Colors.white,
            ),
            child: const Text('Cancel Upload'),
          ),
        ],
      ),
    );
  }
}