- name: Push Analysis Sub-folder to Hugging Face
  env:
      HF_TOKEN: ${{ secrets.HF_TOKEN }}
  run: |
      cd analysis

      # Initialize git repo
      git init -b main
      git config user.name "github-actions"
      git config user.email "github-actions@github.com"

      # Stage and commit
      git add .
      git commit -m "deploy: sync fastapi app to hugging face"

      # Push to HF Spaces
      git remote add space https://juanvictorqwerty:${HF_TOKEN}@huggingface.co/spaces/juanvictorqwerty/AI_Image
      git push --force space main
