name: Sync to Hugging Face Hub

on:
    push:
        branches: [main] # Triggers the workflow whenever you push to your main branch

    # Allows you to manually trigger this workflow from the GitHub Actions tab
    workflow_dispatch:

jobs:
    sync-to-hub:
        runs-on: ubuntu-latest
        steps:
            - name: Checkout Code
              uses: actions/checkout@v4
              with:
                  fetch-depth: 0
                  lfs: true

            - name: Push to Hugging Face Spaces
              uses: huggingface/hub-sync@v0.1.0
              with:
                  github_repo_id: ${{ github.repository }}
                  huggingface_repo_id: juanvic/AI_Image
                  hf_token: ${{ secrets.HF_TOKEN }}
